In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [2]:
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

data = pd.merge(ratings, movies, on='movieId')

In [3]:
data

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...
100831,610,166534,4.0,1493848402,Split (2017),Drama|Horror|Thriller
100832,610,168248,5.0,1493850091,John Wick: Chapter Two (2017),Action|Crime|Thriller
100833,610,168250,5.0,1494273047,Get Out (2017),Horror
100834,610,168252,5.0,1493846352,Logan (2017),Action|Sci-Fi
100835,610,170875,3.0,1493846415,The Fate of the Furious (2017),Action|Crime|Drama|Thriller

In [4]:
user_item_matrix = data.pivot_table(index='userId', columns='title', values='rating')

In [5]:
user_item_matrix.fillna(0, inplace=True)

In [6]:
user_item_matrix

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.5,3.5,0.0,0.0,0.0
609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,...,0.0,4.0,3.5,3.0,0.0,0.0,2.0,1.5,0.0,0.0

In [7]:
user_similarity = cosine_similarity(user_item_matrix)

In [8]:
user_similarity_df = pd.DataFrame(user_similarity, index=user_item_matrix.index, columns=user_item_matrix.index)

In [9]:
user_similarity_df

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.027283,0.059720,0.194395,0.129080,0.128152,0.158744,0.136968,0.064263,0.016875,...,0.080554,0.164455,0.221486,0.070669,0.153625,0.164191,0.269389,0.291097,0.093572,0.145321
2,0.027283,1.000000,0.000000,0.003726,0.016614,0.025333,0.027585,0.027257,0.000000,0.067445,...,0.202671,0.016866,0.011997,0.000000,0.000000,0.028429,0.012948,0.046211,0.027565,0.102427
3,0.059720,0.000000,1.000000,0.002251,0.005020,0.003936,0.000000,0.004941,0.000000,0.000000,...,0.005048,0.004892,0.024992,0.000000,0.010694,0.012993,0.019247,0.021128,0.000000,0.032119
4,0.194395,0.003726,0.002251,1.000000,0.128659,0.088491,0.115120,0.062969,0.011361,0.031163,...,0.085938,0.128273,0.307973,0.052985,0.084584,0.200395,0.131746,0.149858,0.032198,0.107683
5,0.129080,0.016614,0.005020,0.128659,1.000000,0.300349,0.108342,0.429075,0.000000,0.030611,...,0.068048,0.418747,0.110148,0.258773,0.148758,0.106435,0.152866,0.135535,0.261232,0.060792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.164191,0.028429,0.012993,0.200395,0.106435,0.102123,0.200035,0.099388,0.075898,0.088963,...,0.178084,0.116534,0.300669,0.066032,0.148141,1.000000,0.153063,0.262558,0.069622,0.201104
607,0.269389,0.012948,0.019247,0.131746,0.152866,0.162182,0.186114,0.185142,0.011844,0.010451,...,0.092525,0.199910,0.203540,0.137834,0.118780,0.153063,1.000000,0.283081,0.149190,0.139114
608,0.291097,0.046211,0.021128,0.149858,0.135535,0.178809,0.323541,0.187233,0.100435,0.077424,...,0.158355,0.197514,0.232771,0.155306,0.178142,0.262558,0.283081,1.000000,0.121993,0.322055
609,0.093572,0.027565,0.000000,0.032198,0.261232,0.214234,0.090840,0.423993,0.000000,0.021766,...,0.035653,0.335231,0.061941,0.236601,0.097610,0.069622,0.149190,0.121993,1.000000,0.053225
610,0.145321,0.102427,0.032119,0.107683,0.060792,0.052668,0.193219,0.078153,0.074399,0.121072,...,0.222491,0.087528,0.163094,0.052552,0.119295,0.201104,0.139114,0.322055,0.053225,1.000000

In [10]:
def get_top_n_similar_users(user_id, n=10):
    similar_users = user_similarity_df[user_id].sort_values(ascending=False).index[1:n+1]
    return similar_users

In [11]:
# user_id = 1
# user_similarity_df[user_id].sort_values(ascending=False).index[1:10+1]

In [12]:
similar_users = user_similarity_df[user_id].sort_values(ascending=False).index[1:10+1]

NameError: name 'user_id' is not defined

In [ ]:
user_similarity_scores = user_similarity_df[user_id].loc[similar_users]

In [ ]:
similar_users_ratings = user_item_matrix.loc[similar_users]

In [ ]:
user_similarity_scores

userId
266    0.357408
313    0.351562
368    0.345127
57     0.345034
91     0.334727
469    0.330664
39     0.329782
288    0.329700
452    0.328048
45     0.327922
Name: 1, dtype: float64

In [ ]:
weighted_ratings = similar_users_ratings.T.dot(user_similarity_scores) / user_similarity_scores.sum()

In [ ]:
weighted_ratings

title
'71 (2014)                                   0.000000
'Hellboy': The Seeds of Creation (2004)      0.000000
'Round Midnight (1986)                       0.000000
'Salem's Lot (2004)                          0.000000
'Til There Was You (1997)                    0.000000
                                               ...
eXistenZ (1999)                              0.388226
xXx (2002)                                   0.000000
xXx: State of the Union (2005)               0.000000
¡Three Amigos! (1986)                        0.308177
À nous la liberté (Freedom for Us) (1931)    0.000000
Length: 9719, dtype: float64

In [ ]:
user_rated_movies = user_item_matrix.loc[user_id]

In [ ]:
recommendations = weighted_ratings[~user_rated_movies.index.isin(user_rated_movies[user_rated_movies > 0].index)]
recommendations

title
'71 (2014)                                                0.000000
'Hellboy': The Seeds of Creation (2004)                   0.000000
'Round Midnight (1986)                                    0.000000
'Salem's Lot (2004)                                       0.000000
'Til There Was You (1997)                                 0.000000
                                                            ...
anohana: The Flower We Saw That Day - The Movie (2013)    0.000000
eXistenZ (1999)                                           0.388226
xXx (2002)                                                0.000000
xXx: State of the Union (2005)                            0.000000
À nous la liberté (Freedom for Us) (1931)                 0.000000
Length: 9487, dtype: float64

In [ ]:
def get_movie_recommendations(user_id, user_item_matrix, n_recommendations=10):
    similar_users = get_top_n_similar_users(user_id)
    similar_users_ratings = user_item_matrix.loc[similar_users]

    user_similarity_scores = user_similarity_df[user_id].loc[similar_users]
    weighted_ratings = similar_users_ratings.T.dot(user_similarity_scores) / user_similarity_scores.sum()

    user_rated_movies = user_item_matrix.loc[user_id]
    recommendations = weighted_ratings[~user_rated_movies.index.isin(user_rated_movies[user_rated_movies > 0].index)]
   
    top_n_recommendations = recommendations.sort_values(ascending=False).head(n_recommendations).index
    return top_n_recommendations

user_id = 200
recommendations = get_movie_recommendations(user_id, user_item_matrix)
print(f"Top 10 recommendations for user {user_id}:")
for idx, movie in enumerate(recommendations, 1):
    print(f"{idx}. {movie}")

Top 10 recommendations for user 200:
1. Lion King, The (1994)
2. Dogma (1999)
3. V for Vendetta (2006)
4. Departed, The (2006)
5. Lost in Translation (2003)
6. Prestige, The (2006)
7. Ice Age (2002)
8. Beauty and the Beast (1991)
9. Crouching Tiger, Hidden Dragon (Wo hu cang long) (2000)
10. Groundhog Day (1993)